version: '3'

services:
  todotests:
    image: todotests
    restart: always
    depends_on:
      - frontend
      - backend
    environment:
      - FRONT_HOST=todofront
  todofront:
    image: todofrontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
  todoback:
    image: todobackend
    restart: always
    ports:
      - 3001:3001